# Generated by Django 5.0.3 on 2024-03-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
