# Generated by Django 5.0.3 on 2024-03-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='port',
            field=models.IntegerField(default=0, max_length=65565),
            preserve_default=False,
        ),
    ]
